version: '3'

vars:
  SERVER_DEV: khaicafe@192.167.1.200

tasks:
  release:
    vars:
      DOCKER_IMAGE: 192.167.1.200/neocafe/staffweb
      VERSION:
        sh: git tag -l --sort=-v:refname | head -n 1
    cmds:
      - yarn
      - yarn prod
      - docker build -t {{.DOCKER_IMAGE}}:{{.VERSION}} .
      - docker push {{.DOCKER_IMAGE}}:{{.VERSION}}
      - docker rmi {{.DOCKER_IMAGE}}:{{.VERSION}}

  sandbox:
    cmds:
      - yarn sandbox
      - task sync
      - task startcontainer
  sync:
    cmds:
      - rsync -aurv --delete dist {{.SERVER_DEV}}:/root/neocafe/v2/posweb
  startcontainer:
    cmds:
      - ssh {{.SERVER_DEV}} 'cd /root/neocafe/ && docker compose restart posweb'

  dockerlogin:
    vars:
      DOCKER_USERNAME: devops
      DOCKER_PASSWORD: 123456@
    cmds:
      - docker login https://kteam.ddns.net -u {{.DOCKER_USERNAME}} -p {{.DOCKER_PASSWORD}}